### ISSUE TITLE
REST API [GET:/0/search/transactions] on eos mainnet was suspend ?

### ISSUE THREAD

**Issue by Parkjonghyun93** [dfuse-io/docs#115]
Has the REST API service been suspended?

suddenly use api, i get a 404 status response

**Comment by Parkjonghyun93** [comment]
sry! my mistake rest method !

**Comment by sduchesneau** [comment]
Our endpoint `https://mainnet.eos.dfuse.io` has been closed for a few months.
To continue using our service on EOS mainnet, you can either 
1. contact our sales to get a dedicated environment or 
2) move to the dfuse Community Edition, hosted by EOS Nation, available at `https://eos.dfuse.eosnation.io`. However, the community edition does not offer that specific REST endpoint, you will have to migrate to GraphQL: https://docs.dfuse.io/eosio/public-apis/reference/graphql-api/#query-searchtransactionsforward
