### ISSUE TITLE
How should I close the stream in "for rawResult in stream"

### ISSUE THREAD

**Issue by xiangxn** [dfuse-io/docs#62]
How should I close the stream in "for rawResult in stream"

**Comment by maoueh** [comment]
Take at look at https://github.com/grpc/grpc/tree/master/examples/python/cancellation which explain some cancellation concepts around gRPC and the Python generated client.

Tell me if it's good enough, if it's the case, we will add a quick note in the docs to make that information clearer for other developers.

**Comment by xiangxn** [comment]
The performance of blocked stream operations is too bad, I will temporarily use websocket.

**Comment by abourget** [comment]
You can reach out to the team in https://t.me/dfuseAPI to discuss these.

Performances of Search will always be better than the websocket, under normal conditions. I'd be curious to learn more about your use case and/or situation, see if we can improve things for you.

I'll be closing this if you don't mind.
